---
    - name: Setting up iRedMail
      hosts: webserver
      gather_facts: false
      roles:
        - python
#      vars_prompt:
#        - name: iRedMail
#          prompt: 'iRedMail Version (e.g. 0.9.8)'
#          private: no
#        - name: short_hostname
#          prompt: 'short hostname'
#          private: no 
      vars:
        iRedMail: 0.9.8
        short_hostname: mx
        hostname: example
      
      tasks:
        - name: Configuring short hostname
          raw: echo '{{short_hostname}}' > /etc/hostname
#        - name: Enter hostname
#          pause:
#            prompt: 'hostname'
#          register: hostname        
        - name: Lineinfile
          lineinfile:
              path: /etc/hosts
              regexp: '^127\.0\.0\.1'
#              line: '127.0.0.1 {{short_hostname}}.{{hostname.user_input}}.com {{short_hostname}} localhost localhost.localdomain'
              line: '127.0.0.1 {{short_hostname}}.{{hostname}}.com {{short_hostname}} localhost localhost.localdomain'
        - name: Downloading iRedMail-'{{iRedMail}}'.tar.bz2
          raw: wget -c https://bitbucket.org/zhb/iredmail/downloads/iRedMail-{{iRedMail}}.tar.bz2
        - name: Extracting iRedMail-'{{iRedMail}}'
          raw: '{{item}}'
          with_items:
            - tar -xjvf iRedMail-{{iRedMail}}.tar.bz2
            - cd iRedMail-{{iRedMail}}
        - name: Copying install config
          template:
            src: ../../templates/iredmail/config.j2
            dest: 'iRedMail-{{iRedMail}}/config'
        - name: rebooting server
          reboot:
        - name: setting permissions on install script
          file:
            path: 'iRedMail-{{iRedMail}}/iRedMail.sh'
            mode: 0700
        - name: Installing iredmail
          shell: "IREDMAIL_DEBUG='NO' AUTO_USE_EXISTING_CONFIG_FILE=y AUTO_INSTALL_WITHOUT_CONFIRM=y AUTO_CLEANUP_REMOVE_SENDMAIL=y AUTO_CLEANUP_REMOVE_MOD_PYTHON=y AUTO_CLEANUP_REPLACE_FIREWALL_RULES=n AUTO_CLEANUP_RESTART_IPTABLES=n AUTO_CLEANUP_REPLACE_MYSQL_CONFIG=y AUTO_CLEANUP_RESTART_POSTFIX=n bash iRedMail.sh"
          args:
            chdir: '~/iRedMail-{{iRedMail}}'
        - raw: service postfix restart
#          notify: restart stack
#        - name: Installing iRedMail 
#          expect:
#            command: bash iRedMail.sh
#            chdir: '~/iRedMail-{{iRedMail}}'
#            responses:
#                Question:
#                    - 'y'
#                    - 'n'
#                    - 'it for mail server': 'y'
#                  '.*ould you like to use firewall .*': 'n'
#                    - 'with SSHD port': 'n'
#            echo: yes

       
