---
#    - name: Installing wordpress
#      hosts: webserver
#      gather_facts: false
#      vars_prompt:       
#        - name: wp_db_name
#          prompt: 'database name'
#          private: no
#        - name: wp_path
#          prompt: 'path (eg. /var/www/test)'
#          private: no
#      roles:
#        - python 
#      tasks:
        #- name: install python
        #  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        
        - name: Install nginx
          apt:
            update_cache: yes
            name: nginx
            state: present
        
        #- name: configure nginx remove existing conf
        #  file:
        #    path: /etc/nginx/sites-available/*
        #    state: absent
        
        - name: remove nginx conf default files
          raw: rm -rf /etc/nginx/sites-enabled/*       
        
        - name: configure nginx add custom conf
          template:
            src: nginx.conf.j2 
            dest: /etc/nginx/sites-available/wp-nginx.conf
          notify: restart nginx
        
        - name: configure nginx link those shit
          file:
            src: /etc/nginx/sites-available/wp-nginx.conf
            dest: /etc/nginx/sites-enabled/wp-nginx.conf
            state: link
          notify: restart nginx
        
        #- name: Ensure nginx started
        #  service:
        #    name: nginx
        #    state: started
        #    enabled: yes

        - name: Install mysql
          apt:
            name: ['mysql-server', 'mysql-client', 'python-mysqldb']
            state: present

        - mysql_user:
#            login_user: root 
#            login_password: Hello101!
#            create mysql user
            name: '{{wp_db_name}}'
            password: Hello101!
            update_password: always
            priv: '*.*:ALL'
            state: present

        - name: Create wordpress database
          mysql_db:
            login_user: '{{wp_db_name}}'
            login_password: Hello101!
            name: '{{wp_db_name}}'
            state: present
            
        - name: Install php
          apt:
            name: ['php', 'php-mysql', 'php-cgi', 'php-cli', 'php-gd']
            state: present

        - name: Install wordpress
          raw: "{{item}}"
          with_items:
            - 'wget -c http://wordpress.org/latest.tar.gz'
            - 'tar -xzvf latest.tar.gz'
            - 'rsync -av wordpress/* /var/www/{{wp_db_name}}/'

        
        - name: configure wp remove existing wp-config
          template:
            src: wp-config.php.j2
            dest: '/var/www/{{wp_db_name}}/wp-config.php'
          notify: restart nginx

        - name: Set permission
          raw: '{{item}}'
          with_items:
            - 'chown -R www-data:www-data /var/www/{{wp_db_name}}/'
            - 'chmod -R 755 /var/www/{{wp_db_name}}/'


