---

        - name: Configuring short hostname
          raw: echo '{{short_hostname}}' > /etc/hostname
        - name: Lineinfile
          lineinfile:
              path: /etc/hosts
              regexp: '^127\.0\.0\.1'
              line: '127.0.0.1 {{short_hostname}}.{{hostname}}.com {{short_hostname}} localhost localhost.localdomain'
        - name: Downloading iRedMail-'{{iRedMail}}'.tar.bz2
          raw: wget -c https://bitbucket.org/zhb/iredmail/downloads/iRedMail-{{iRedMail}}.tar.bz2
        - name: Extracting iRedMail-'{{iRedMail}}'
          raw: '{{item}}'
          with_items:
            - tar -xjvf iRedMail-{{iRedMail}}.tar.bz2
            - cd iRedMail-{{iRedMail}}
        - name: Copying install config
          template:
            src: config.j2
            dest: 'iRedMail-{{iRedMail}}/config'
        - name: rebooting server
          reboot:
        - name: setting permissions on install script
          file:
            path: 'iRedMail-{{iRedMail}}/iRedMail.sh'
            mode: 0700
        - name: Installing iredmail
          shell: "IREDMAIL_DEBUG='NO' AUTO_USE_EXISTING_CONFIG_FILE=y AUTO_INSTALL_WITHOUT_CONFIRM=y AUTO_CLEANUP_REMOVE_SENDMAIL=y AUTO_CLEANUP_REMOVE_MOD_PYTHON=y AUTO_CLEANUP_REPLACE_FIREWALL_RULES=n AUTO_CLEANUP_RESTART_IPTABLES=n AUTO_CLEANUP_REPLACE_MYSQL_CONFIG=y AUTO_CLEANUP_RESTART_POSTFIX=y bash iRedMail.sh"
          args:
            chdir: '~/iRedMail-{{iRedMail}}'          
        - name: configuring nginx for iredmail
          template:
            src: iredmail_nginx.conf.j2
            dest: /etc/nginx/sites-available/00-default-ssl.conf

        - name: rebooting server
          reboot:
      
